### ISSUE TITLE
Acronyms should have a consistent case

### ISSUE THREAD

**Issue by velovix** [go-audio/audio#1]
According to the [Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms) document, which provides style guidelines for Go code:

> Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case. For example, "URL" should appear as "URL" or "url" (as in "urlPony", or "URLPony"), never as "Url". Here's an example: ServeHTTP not ServeHttp.

For that reason, I think functions `IeeeFloatToInt` and `IntToIeeeFloat` should be renamed to `IEEEFloatToInt` and `IntToIEEEFloat`, respectively.

I know this is bikeshedding, but if this library is to become an official interface for Go audio, I think this kind of stuff is somewhat important.

**Comment by mattetti** [comment]
I agree, would you mind sending a PR (I'll fix the other repos and add Travis integration)

**Comment by velovix** [comment]
Sure!

**Comment by velovix** [comment]
https://github.com/go-audio/audio/pull/2
