### ISSUE TITLE
int buffers should track the bit depth of the input

### ISSUE THREAD

**Issue by mattetti** [go-audio/audio#8]
because of the float conversion, we need to track the bit depth of the input so we can properly scale the input. Currently the code expects an int16 input which is wrong.

**Comment by egonelbre** [comment]
Wouldn't using `Int16Buffer` be a sufficient solution or would it throw off some other design consideration?

Which code expects the int16? I mean if this is the source or sink of the pipeline, then the corresponding endpoint could take care of correctly scaling the Float buffer?

**Comment by mattetti** [comment]
Here is the issue: https://github.com/go-audio/audio/blob/master/audio.go#L210
```go
float32(float64(int16(buf.Data[i])) / math.Pow(2, 8*2-1))
```

```math.Pow(2, 8*2-1)``` assumes that the bit depth of the int is 2 bytes, but if the sample was a 24bit sample, I don't think the result will be correct.

**Comment by egonelbre** [comment]
I think the fundamental issue is that IntBuffer isn't with specific width. I.e. it probably should be Int32Buffer.

This also means that when storing uint8, int8, uint16, int16, int24, int48 etc.. will hit similar issue. Plus the additional issue, when running on 32bit, and storing int48, then the potential clipping.

**Comment by mattetti** [comment]
I agree, I'm planning on redoing the implementation more like what I had at the beginning with a generic buffer backed by different types so we can workaround these issues without making the API super complicated.

**Comment by mattetti** [comment]
I worked around the issue by having a new source bitdepth field in the buffer and when doing the conversion if the field isn't set, I try to guess it. It's not ideal but it should work most of the time. I also updated the PCM decoders to set those fields.
